test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

development:
  service: Disk
  root: <%= Rails.root.join("storage") %>


# Use bin/rails credentials:edit to set the GCP Storage secret (as gcp_storage:storage_access_key)
#   storage_access_key: <%= Rails.application.credentials.dig(:gcp_storage, :storage_access_key) %>

# Remember not to checkin your GCS keyfile to a repository
google:
  service: GCS
  project: <%= ENV['PROJECT_ID'] %>
  credentials: <%= Rails.root.join("private/sa.json") %>
  # TODO(ricc): set up thos for public access:
  # https://cloud.google.com/storage/docs/access-control/making-data-public?hl=it#buckets
  bucket: <%= ENV['GCS_BUCKET'] %>
  #bucket: genai-kids-stories-<%= Rails.env %>
  #cache_control: "public, max-age=3600"
  # doesnt work on G policies :/
  #public: true


# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]

dev-on-gcp: # This use GCP for Rails Storage and Pgsql for DB
  service: Mirror
  primary: local
  mirrors:
    - google

production:
  service: Mirror
  primary: local
  mirrors:
    - google
