###########################################
# Hi Riccardo, here's where Im invoked: https://console.cloud.google.com/cloud-build/triggers/edit/3ea0601e-3544-4385-ab5a-f4c7f7aceb4c?hl=IT&project=ror-goldie
# See CloudBuild samples: https://github.com/GoogleCloudPlatform/cloud-build-samples/blob/main/run-example-builddeploy/cloudbuild.yaml
###########################################
# 20min for RoR :/
timeout: 1200s
options:
  machineType: 'N1_HIGHCPU_8'
  # This allows for missing ENV variables.
  substitution_option: 'ALLOW_LOOSE'
tags: ['rails', 'genai', 'gh' , 'devrel', 'ruby' ]
images:
  #2. But build is on ror-goldie, so trying this instead since CB works on steps 1/2!
  - "${_ARTIFACT_REPO_ALL}:cb-latest" # Artifact Repo!
  - "${_ARTIFACT_REPO_ALL}:sha-$SHORT_SHA"
substitutions:
  #_PROJECT_ID: ror-goldie
  _REGION: europe-west1
  _ARTIFACT_REPO_ALL: "europe-north1-docker.pkg.dev/ror-goldie/genai/genai-kids-stories"
  _ARTIFACT_REPO: "europe-north1-docker.pkg.dev/ror-goldie/genai"
steps:

# - name: 'ruby:3.2.0'
#   id: Ruby rake test ideally before anything else..
#   args: ['bundle', 'exec', 'rake', 'test']

  #### DOCKER BUILD
-  name: 'gcr.io/cloud-builders/docker'
   id: 2 Docker Build - to LATEST
   args: ['build', '-t', "${_ARTIFACT_REPO_ALL}:cb-latest", '.']
   dir: .
-  name: 'gcr.io/cloud-builders/docker'
   id: 3 Tag latest to vVERSION
   args:
    - 'tag'
    - "${_ARTIFACT_REPO_ALL}:cb-latest"
    - "${_ARTIFACT_REPO_ALL}:sha-$SHORT_SHA"
   dir: .

  #### DOCKER PUSH
  # I think its useless
#  - name: 'gcr.io/cloud-builders/docker'
#    id: Docker push CB LATEST
#    args: ['push', "${_ARTIFACT_REPO_ALL}:cb-latest"]

#  - name: 'gcr.io/cloud-builders/docker'
#    id: Docker push vSHA
#    args: ['push', "${_ARTIFACT_REPO_ALL}:sha-$SHORT_SHA"]


#  - name: 'ruby:3.2.0'
#    id: 3 Ruby rake test ok if it fails
#    args: ['rake || echo ok anyway']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  -   'deploy'
  -      'genai-kid-stories-cb-latest'
  # better SHA than latest. now its the same, but tomorrow might make a difference..
  # I mean, we push at every build but you never know..
  - '--image'
  -   "${_ARTIFACT_REPO_ALL}:sha-$SHORT_SHA"
  - '--region'
  -   "${_REGION}"
  - '--platform'
  -   'managed'
  - '--allow-unauthenticated'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - 'bin/deploy-to-cloud-run'
  dir: .
  env:
  - 'REGION=${_REGION}'
  - 'ARTIFACT_REPO=${_ARTIFACT_REPO}'
  secretEnv:
  - 'DANGEROUS_SA_JSON_VALUE'

  # DANGEROUS_SA_JSON_VALUE
  # secretEnv:
  #   - null
  # ARTIFACT_REPO:

- name: 'bash'
  id: 3 Prova Bash del menga da togliere per vedere Articoli in DEV
  args: ['echo', 'User.count', '|', 'rails', 'c']
  dir: .

availableSecrets:
  secretManager:

  # https://console.cloud.google.com/security/secret-manager?referrer=search&e=-13802955&project=ror-goldie
  - versionName: projects/ror-goldie/secrets/genai-service-account/versions/latest
    env: 'DANGEROUS_SA_JSON_VALUE'
#  - versionName: projects/PROJECT_ID/secrets/DOCKER_PASSWORD_SECRET_NAME/versions/DOCKER_PASSWORD_SECRET_VERSION
#    env: 'PASSWORD'
#  - versionName: projects/PROJECT_ID/secrets/DOCKER_USERNAME_SECRET_NAME/versions/DOCKER_USERNAME_SECRET_VERSION
#    env: 'USERNAME'
